[package]
name = "common"
version = "0.1.0"
authors = ["roychiang"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.6", features = ["full"] }
async-trait = "0.1"