apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  serviceName: scheduler
  replicas: 3
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: webhook
        image: {{ .Values.image }}
        command: [./scheduler]
        args:
        - /etc/settings/settings.yaml
        env:
        - name: RUST_LOG
          value: info
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
