apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: crosscent/telegram:latest
        args:
        - /etc/settings/settings.yaml
        env:
        - name: RUST_LOG
          value: info
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: settings-volume
          mountPath: /etc/settings
      volumes:
      - name: settings-volume
        configMap:
          name: settings